# Generated by Django 3.2.9 on 2021-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=10, verbose_name='Sinflar_nomi')),
                ('number', models.IntegerField(verbose_name="O'quvchilar_soni")),
                ('classroom', models.IntegerField(verbose_name='Biriktirilgan_xona')),
                ('leader', models.CharField(max_length=50, verbose_name='Rahbari')),
                ('part', models.IntegerField(verbose_name='Smenasi')),
                ('image', models.ImageField(upload_to='Sinflar/', verbose_name='Surati')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
    ]
