# Generated by Django 3.2.9 on 2021-12-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oquvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FISH')),
                ('class_name', models.CharField(max_length=5, verbose_name='Sinfi')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('adress', models.CharField(max_length=300, verbose_name='Yashash manzili')),
                ('image', models.ImageField(upload_to='oquvchilar/', verbose_name='Surati')),
            ],
            options={
                'verbose_name': 'Oquvchi',
                'verbose_name_plural': 'Oquvchilar',
            },
        ),
    ]
