# Generated by Django 3.2.9 on 2021-12-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FISH')),
                ('position', models.CharField(max_length=40, verbose_name='Lavozimi')),
                ('age', models.IntegerField(max_length=5, verbose_name='Yoshi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('level', models.CharField(max_length=40, verbose_name='Malumoti')),
                ('salary', models.IntegerField(max_length=10, verbose_name='Maoshi')),
                ('image', models.ImageField(upload_to='oqituvchi/', verbose_name='Surati')),
            ],
            options={
                'verbose_name': 'Oqituvchi',
                'verbose_name_plural': 'Oqituvchilar',
            },
        ),
    ]
