# Generated by Django 3.2.9 on 2021-12-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oqituvchilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oqituvchilar',
            name='age',
            field=models.IntegerField(verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='oqituvchilar',
            name='salary',
            field=models.IntegerField(verbose_name='Maoshi'),
        ),
    ]
