# Generated by Django 3.2.9 on 2021-12-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rahbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FISH')),
                ('position', models.CharField(max_length=20, verbose_name='Lavozim')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoni')),
                ('level', models.CharField(max_length=20, verbose_name='Malumoti')),
                ('image', models.ImageField(upload_to='rahbariyat/', verbose_name='Rasm')),
            ],
        ),
    ]
