# Generated by Django 3.2.9 on 2021-12-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rahbariyat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbar',
            name='level',
            field=models.CharField(max_length=30, verbose_name='Malumoti'),
        ),
        migrations.AlterField(
            model_name='rahbar',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Lavozim'),
        ),
    ]
