# Generated by Django 3.2.9 on 2021-12-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rahbariyat', '0002_auto_20211215_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rahbar',
            options={'verbose_name': 'Rahbar', 'verbose_name_plural': 'Rahbarlar'},
        ),
    ]
